function random_greet() {
  adjs = [ "buon",
           "felice",
           "gioioso",
           "muschiato",
           "euforico",
           "fantastico",
           "incredibile",
           "distinto",
           "viscoso",
           "profumato",
           "appassionato",
           "silenzioso",
           "ruvido",
           "tiepido",
           "dolce",
           "salato",
           "ricco",
           "emblematico",
           "simpatico",
           "vaporoso",
           "estatico",
           "meditabondo",
           "illuminato",
           "cospicuo",
           "concreto",
           "temporaneo",
           "perenne",
           "sano",
           "critico",
           "fortunato",
           "fantasmagorico",
           "impeccabile",
           "impellicciato",
           "esilarante",
           "variopinto",
           "gustoso",
           "distanziato",
           "affettuoso",
           "complementare",
           "supplementare",
           "carico",
           "quantico",
           "classico",
           "oggettivo",
           "indimenticabile",
           "nucleare",
           "compilato",
           "interpretato",
           "trascendente",
           "armonioso",
           "grasso"
         ];
  adj1 = adjs[Math.floor(Math.random() * adjs.length)];
  adj2 = adjs[Math.floor(Math.random() * adjs.length)];
  document.getElementById("greet").innerHTML = "Tanti auguri di un " + adj1 + " Natale e di un " + adj2 + " anno nuovo!";
}
